# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='Appname',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='Availibity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Bamplus',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='Bamplusid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Confidentiality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Developpment',
            field=models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('SHARE', 'SHARE')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='Integrity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Tracability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='ciso_perim',
            field=models.CharField(default='null', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='compliant_based_ident',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='criticity_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='fsa',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='fsa_level',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='gsf_lastdate',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='gsf_uptodate',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='hosting',
            field=models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('SHARE', 'SHARE')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='https',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='internet_facing',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='n_tier',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='production_review',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='role_base_access_control',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='sensitivity_level',
            field=models.CharField(choices=[('SERIOUS', '4'), ('EXTREME', '3'), ('MODERATE', '2'), ('LOW', '1')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='siem',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='ssl',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='tls',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='waf',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
    ]
