# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20170914_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Developpment',
            field=models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('SHARE', 'SHARE')], default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sensitivity_level',
            field=models.CharField(choices=[('4', 'SERIOUS'), ('3', 'EXTREME'), ('2', 'MODERATE'), ('1', 'LOW')], default='null', max_length=10),
        ),
    ]
