# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_auto_20170914_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Availibity',
            field=models.IntegerField(choices=[('4', 'SERIOUS'), ('3', 'EXTREME'), ('2', 'MODERATE'), ('1', 'LOW')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Confidentiality',
            field=models.IntegerField(choices=[('4', 'SERIOUS'), ('3', 'EXTREME'), ('2', 'MODERATE'), ('1', 'LOW')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Integrity',
            field=models.IntegerField(choices=[('4', 'SERIOUS'), ('3', 'EXTREME'), ('2', 'MODERATE'), ('1', 'LOW')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tracability',
            field=models.IntegerField(choices=[('4', 'SERIOUS'), ('3', 'EXTREME'), ('2', 'MODERATE'), ('1', 'LOW')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='hosting',
            field=models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('SHARE', 'SHARE')], default='null', max_length=15),
        ),
    ]
