# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_auto_20170914_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='criticity_level',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], default=0, max_length=15),
        ),
    ]
