# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_auto_20170914_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appname', models.CharField(default='null', max_length=100)),
                ('Bamplus', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=5)),
                ('Bamplusid', models.IntegerField(default=0)),
                ('Confidentiality', models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], default=0, max_length=15)),
                ('Integrity', models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], default=0, max_length=15)),
                ('Availibity', models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], default=0, max_length=15)),
                ('Tracability', models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], default=0, max_length=15)),
                ('ciso_perim', models.CharField(default='null', max_length=25)),
                ('compliant_based_ident', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5)),
                ('criticity_level', models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], default=0, max_length=15)),
                ('Developpment', models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('SHARE', 'SHARE')], default='null', max_length=10)),
                ('fsa', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5)),
                ('fsa_level', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5)),
                ('gsf_uptodate', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5)),
                ('gsf_lastdate', models.CharField(default='null', max_length=15)),
                ('hosting', models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('SHARE', 'SHARE')], default='null', max_length=15)),
                ('https', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5)),
                ('internet_facing', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5)),
                ('n_tier', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5)),
                ('production_review', models.CharField(default='null', max_length=15)),
                ('role_base_access_control', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5)),
                ('sensitivity_level', models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], default='null', max_length=10)),
                ('siem', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5)),
                ('ssl', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5)),
                ('tls', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5)),
                ('waf', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pentest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.AppList')),
            ],
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
