# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_auto_20170924_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='pentest',
            name='auditor',
            field=models.CharField(choices=[('Beijaflore', 'Beijaflore'), ('Nes', 'Nes'), ('Gfi', 'Gfi'), ('ISPL', 'ISPL'), ('AppSecTeam', 'AppSecTeam')], default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='pentest',
            name='pilote',
            field=models.CharField(choices=[('dla', 'Damien Lallement'), ('ala', 'Alexandre Lasnier'), ('...', '...')], default='null', max_length=15),
        ),
        migrations.AlterField(
            model_name='pentest',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
