# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_auto_20170924_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='pentest',
            name='critical_vulnerability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pentest',
            name='high_vulnerability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pentest',
            name='low_vulnerability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pentest',
            name='medium_vulnerability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pentest',
            name='total_vulnerability',
            field=models.IntegerField(default=0),
        ),
    ]
