# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0015_auto_20170924_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='applist',
            name='Instance',
            field=models.CharField(default='null', max_length=100, unique=True),
        ),
    ]
