# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_applist_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applist',
            name='Instance',
        ),
    ]
