# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_applist_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applist',
            name='production_review',
        ),
        migrations.AddField(
            model_name='applist',
            name='last_production_review',
            field=models.DateTimeField(blank=True, null=True, verbose_name='production review'),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Appname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Availibity',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Bamplus',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('YES', 'YES'), ('NO', 'NO')], default='CHOICE', max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Confidentiality',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], default='CHOICE', max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Developpment',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('SHARE', 'SHARE')], default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Instance',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Integrity',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Tracability',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='ciso_perim',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='applist',
            name='compliant_based_ident',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='criticity_level',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='fsa',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='fsa_level',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='gsf_lastdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='applist',
            name='gsf_uptodate',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='hosting',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('SHARE', 'SHARE')], default='null', max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='https',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='internet_facing',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='n_tier',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='role_base_access_control',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='sensitivity_level',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='applist',
            name='siem',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='ssl',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='tls',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='waf',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('YES', 'YES'), ('NO', 'NO')], default='null', max_length=5),
        ),
    ]
