# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0019_auto_20170924_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applist',
            name='Availibity',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Bamplus',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Confidentiality',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Developpment',
            field=models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('SHARE', 'SHARE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Integrity',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Tracability',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='compliant_based_ident',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='criticity_level',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='fsa',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='fsa_level',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='gsf_uptodate',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='hosting',
            field=models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('SHARE', 'SHARE')], max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='https',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='internet_facing',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='n_tier',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='role_base_access_control',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='sensitivity_level',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=10),
        ),
        migrations.AlterField(
            model_name='applist',
            name='siem',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='ssl',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='tls',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applist',
            name='waf',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pentest',
            name='auditor',
            field=models.CharField(choices=[('BF', 'Beijaflore'), ('Nes', 'Nes'), ('Gfi', 'Gfi'), ('ISPL', 'ISPL'), ('AST', 'AppSecTeam')], default='null', max_length=15),
        ),
    ]
