# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0022_vulnerability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='status_remediation',
            field=models.CharField(choices=[('NA', 'No Assignee'), ('OP', 'Open'), ('IP', 'In-Progress'), ('SB', 'Submit-for-closure'), ('CL', 'Clos')], max_length=15),
        ),
    ]
