# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0023_auto_20170929_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applist',
            name='waf',
        ),
    ]
