# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0024_remove_applist_waf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text_message', models.CharField(max_length=400)),
                ('deadline_remediation', models.DateTimeField(auto_now_add=True)),
                ('scope_link', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='backoffice.Pentest')),
                ('target_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.AppList')),
                ('vulnerability_link', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='backoffice.Vulnerability')),
            ],
        ),
    ]
