# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0025_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servname', models.CharField(max_length=100, unique=True)),
                ('ip', models.CharField(max_length=100, unique=True)),
                ('hosting', models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('SHARE', 'SHARE')], max_length=5)),
                ('os', models.CharField(choices=[('W', 'Windows'), ('U', 'Unix'), ('L', 'Linux'), ('M', 'Macintosh')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='applist',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='scope_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Pentest'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vulnerability_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Vulnerability'),
        ),
        migrations.AddField(
            model_name='applist',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.ServerList'),
        ),
    ]
