# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0026_auto_20171002_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='hosting',
            field=models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('SHARE', 'SHARE')], max_length=10),
        ),
    ]
