# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0029_auto_20171002_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applist',
            name='Availibity',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Bamplus',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Bamplusid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Confidentiality',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Developpment',
            field=models.CharField(choices=[('INTERNAL', 'INTERNAL'), ('EXTERNAL', 'EXTERNAL'), ('SHARE', 'SHARE')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Integrity',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Tracability',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='ciso_perim',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='compliant_based_ident',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='fsa',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='fsa_level',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='gsf_lastdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='gsf_uptodate',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='n_tier',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='role_base_access_control',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='siem',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='ssl',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applist',
            name='tls',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True),
        ),
    ]
