# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0032_auto_20171003_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pentest',
            name='auditor',
            field=models.CharField(choices=[('Beijaflore', 'Beijaflore'), ('Nes', 'Nes'), ('Gfi', 'Gfi'), ('ISPL', 'ISPL'), ('AST', 'AppSecTeam')], default='null', max_length=15),
        ),
    ]
