# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0033_auto_20171017_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applist',
            name='Availibity',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Confidentiality',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Integrity',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=15),
        ),
        migrations.AlterField(
            model_name='applist',
            name='Tracability',
            field=models.CharField(choices=[('4', 'EXTREME'), ('3', 'SERIOUS'), ('2', 'MODERATE'), ('1', 'LOW')], max_length=15),
        ),
    ]
