# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0034_auto_20171219_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='applist',
            name='lpm',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5),
        ),
        migrations.AddField(
            model_name='applist',
            name='lpm_level',
            field=models.CharField(blank=True, choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=5),
        ),
    ]
